language: python
python:
  - "3.5"
sudo: required
services:
  - docker
branches:
  only:
  - sources
env:
  global:
    secure: "xxxxxxxxxxxx"
install:
- pip install ghp-import
- git clone https://github.com/volleyballing/volleyballing.github.io
script:
- make publish github